model_list:
  - model_name: "gemini/gemini-2.5-flash"
    litellm_params:
      model: "gemini/gemini-2.5-flash"
  - model_name: "gemini/gemini-3-flash-preview"
    litellm_params:
      model: "gemini/gemini-3-flash-preview"
  - model_name: "gemini/*"
    litellm_params:
      model: "gemini/*"

litellm_settings:
  # Do not drop invalid params from the request unless necessary
  drop_params: true
  set_verbose: true
